services:
  rasa:
    build:
      context: ./rasa
      dockerfile: Dockerfile
    container_name: rasa_bot
    ports:
      - "5005:5005"
    volumes:
      - ./models:/app/models # ✅ Use pretrained model
      - ./logs:/app/logs
    environment:
      RASA_ENV: production
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - redis
      - action-server
    command:
      - run
      - --enable-api
      - --cors
      - "*"
      - --debug
    networks:
      - faqnet

  action-server:
    image: rasa/rasa-sdk:3.6.2
    container_name: rasa_actions
    volumes:
      - ./actions:/app/actions
    ports:
      - "5055:5055"
    command:
      - start
      - --actions
      - actions
    networks:
      - faqnet

  redis:
    image: redis:7
    container_name: rasa_redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    networks:
      - faqnet

  frontend:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./frontend/index.html:/usr/share/nginx/html/index.html:ro
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: faq-frontend
    networks:
      - faqnet

networks:
  faqnet:
    driver: bridge